config/routes.rb
Rails.application.routes.draw do
  get "/", to: redirect("/#{I18n.default_locale}"), constraints: ->(req) { req.params[:locale].blank? }
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

    # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
    # Can be used by load balancers and uptime monitors to verify that the app is live.
    get "up" => "rails/health#show", as: :rails_health_check

    # Defines the root path route ("/")
    # root "posts#index"

    root to: "pages#home"

    get "pages/language_learning"

    get "pages/programming_services"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  around_action :switch_locale

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end

  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def language_learning
  end

  def programming_services
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
  <head>
    <meta charset="utf-8">
    <title>Jobusinesswebsite</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "components/language_switch" %>
    <%= yield %>
    <%# console %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="welcome-message-container">
  <h1><%= translate ".home_welcome" %></h1>
</div>


<div class="home-page-btn-container">
<div class="home-page-btn-div">
<%= link_to t('.home_language_btn'), pages_language_learning_path(locale: I18n.locale), class: "home-page-btn", style: "background-image: url(#{asset_path('classroom-stockimage.jpg')});" %>
</div>
<div class="home-page-btn-div">
<%= link_to t('.home_programming_btn'), pages_programming_services_path(locale: I18n.locale), class: "home-page-btn", style: "background-image: url(#{asset_path('coding-background-image.png')});" %>
</div>
</div>